import { test, expect } from '@playwright/test'

test('compact menus retain file actions, keyboard navigation and full preview at phone widths', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/')
  await expect(page.locator('.preview-container svg .node').first()).toBeVisible()
  const viewport = (await page.locator('.preview-viewport').boundingBox())!
  const diagram = (await page.locator('.preview-content svg').boundingBox())!
  expect(diagram.y).toBeGreaterThanOrEqual(viewport.y)
  expect(diagram.y + diagram.height).toBeLessThanOrEqual(viewport.y + viewport.height)
  expect(viewport.y + viewport.height).toBeLessThanOrEqual(740)
  const toolbar = page.getByRole('navigation', { name: 'Workspace actions' })
  for (const name of ['New', 'File', 'Export…', 'View', 'Chat', 'Decisions', 'Settings']) {
    const button = toolbar.getByRole('button', { name, exact: true })
    await expect(button).toBeVisible()
    const box = (await button.boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(320)
  }
  await toolbar.getByRole('button', { name: 'File', exact: true }).focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Import diagram…' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Knowledge base / RAG…' })).toBeFocused()
  await expect(page.getByRole('menuitem')).toHaveCount(4)
  const menu = (await page.getByRole('menu', { name: 'File' }).boundingBox())!
  expect(menu.x + menu.width).toBeLessThanOrEqual(320)
  await page.keyboard.press('Escape')
  await expect(toolbar.getByRole('button', { name: 'File', exact: true })).toBeFocused()
  await toolbar.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Full preview', exact: true }).click()
  await expect(page.locator('.editor-container')).toHaveCount(0)
  await toolbar.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Show editor', exact: true }).click()
  await expect(page.locator('.editor-container')).toBeVisible()
  await toolbar.getByRole('button', { name: 'Chat', exact: true }).click()
  const chat = (await page.locator('.chat-panel').boundingBox())!
  expect(chat.x).toBeGreaterThanOrEqual(0)
  expect(chat.x + chat.width).toBeLessThanOrEqual(320)
  await page.getByTitle('Decisions (Preview)').click()
  await expect(page.locator('.decision-workspace')).toBeVisible()
  await page.keyboard.press('Control+j')
  await expect(page.locator('.decision-workspace')).toHaveCount(0)
  await expect(page.locator('.chat-panel')).toBeVisible()
})

test('settings sections keep drafts, independent embeddings, readable selections and keyboard focus', async ({ page }) => {
  await page.goto('/')
  await page.getByTitle('Settings').click()
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  await expect(dialog.getByRole('tab', { name: 'Connection', exact: true })).toBeFocused()
  await page.locator('#ollama-model').fill('my-chat-model')
  await page.getByRole('tab', { name: 'Embeddings', exact: true }).click()
  await page.locator('#embed-provider-openai').click()
  await page.locator('#openai-embedding-model').fill('text-embedding-3-small')
  await page.getByRole('tab', { name: 'Generation', exact: true }).click()
  await page.locator('#ollama-system-prompt').fill('Keep labels short.')
  await page.getByRole('tab', { name: 'Connection', exact: true }).click()
  await expect(page.locator('#ollama-model')).toHaveValue('my-chat-model')
  for (const theme of ['dark', 'light']) {
    const colors = await page.locator('#provider-tab-ollama').evaluate(element => {
      const style = getComputedStyle(element)
      return { text: style.color, background: style.backgroundColor }
    })
    expect(colors.text, theme).not.toBe(colors.background)
    await page.getByRole('tab', { name: 'Appearance', exact: true }).click()
    await page.getByRole('button', { name: `Use ${theme === 'dark' ? 'light' : 'dark'}` }).click()
    await page.getByRole('tab', { name: 'Connection', exact: true }).click()
  }
  page.once('dialog', dialog => dialog.accept())
  await page.locator('#settings-save').click()
  await expect(page.getByTitle('Settings')).toBeFocused()
  const config = await page.evaluate(() => JSON.parse(localStorage.getItem('ollama-config')!))
  expect(config.provider).toBe('ollama')
  expect(config.embeddingProvider).toBe('openai')
  expect(config.model).toBe('my-chat-model')
  expect(config.openaiEmbeddingModel).toBe('text-embedding-3-small')
  expect(config.systemPrompt).toBe('Keep labels short.')
  await page.getByTitle('Settings').click()
  await page.keyboard.press('ArrowRight')
  await expect(dialog.getByRole('tab', { name: 'Embeddings' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByTitle('Settings')).toBeFocused()
  await page.getByTitle('Settings').click()
  await page.locator('#settings-save').focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close settings' })).toBeFocused()
})

test('blob animation respects device preferences, keeps identity and leaves the diagram stable', async ({ page }) => {
  await page.goto('/')
  const blob = page.locator('.toolbar .user-blob')
  await expect(blob.locator('svg .mo-always')).toBeVisible()
  await expect(page.locator('.preview-container svg .node').first()).toBeVisible()
  let diagram = await page.locator('.preview-container svg').getAttribute('id')
  const profile = await blob.getAttribute('data-profile-id')
  const body = await blob.locator('.mo-breathe').evaluate(element => getComputedStyle(element).animationName)
  expect(body).toBe('mo-breathe')
  await page.setViewportSize({ width: 320, height: 740 })
  await expect.poll(() => page.locator('.preview-container svg').getAttribute('id')).not.toBe(diagram)
  diagram = await page.locator('.preview-container svg').getAttribute('id')
  await page.getByTitle('Settings').click()
  for (const section of ['Connection','Embeddings','Generation','Appearance']) {
    const box = (await page.getByRole('tab', { name: section, exact: true }).boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(320)
  }
  await page.getByRole('tab', { name: 'Appearance', exact: true }).click()
  await page.locator('#settings-blob-motion').uncheck()
  await expect(blob.locator('img')).toBeVisible()
  await page.keyboard.press('Escape')
  expect(await page.locator('.preview-container svg').getAttribute('id')).toBe(diagram)
  await page.reload()
  await expect(blob.locator('img')).toBeVisible()
  expect(await blob.getAttribute('data-profile-id')).toBe(profile)
  await page.getByTitle('Settings').click()
  await page.getByRole('tab', { name: 'Appearance', exact: true }).click()
  await page.locator('#settings-blob-motion').check()
  await expect(blob.locator('svg')).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(blob.locator('img')).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(blob.locator('svg')).toBeVisible()
})

test('diagram labels have readable contrast against the workspace in both themes', async ({ page }) => {
  await page.goto('/')
  const label = page.locator('.preview-container svg .node .nodeLabel').first()
  await expect(label).toBeVisible()
  const darkInk = await label.evaluate(element => getComputedStyle(element).color)
  expect(darkInk).toBe('rgb(226, 232, 240)')
  const oldId = await page.locator('.preview-container svg').getAttribute('id')
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch to light theme' }).click()
  await expect.poll(() => page.locator('.preview-container svg').getAttribute('id')).not.toBe(oldId)
  expect(await label.evaluate(element => getComputedStyle(element).color)).toBe('rgb(51, 65, 85)')
})
