import { test, expect } from '@playwright/test'

test.use({ viewport: { width: 402, height: 874 }, isMobile: true, hasTouch: true })

test('touch menus, searchable diagrams and fullscreen floating windows fit phone screens', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button',{name:'View',exact:true}).tap()
  await page.getByRole('menuitem',{name:'Switch to light theme'}).tap()
  await expect(page.locator('.app')).toHaveClass(/light/)
  await page.getByRole('button',{name:'File',exact:true}).tap()
  await page.getByRole('menuitem',{name:'Knowledge base / RAG…'}).tap()
  await expect(page.locator('.kb-modal')).toBeVisible()
  await page.locator('.kb-header .close-button').tap()
  await page.getByRole('button',{name:/^Diagrams/}).tap()
  await page.getByRole('searchbox',{name:'Search diagrams'}).fill('Action 1')
  await expect(page.locator('.diagram-result-select')).toHaveCount(1)
  await page.locator('.diagram-result-select').tap()
  await page.getByRole('button',{name:'View',exact:true}).tap()
  await page.getByRole('menuitem',{name:'Fullscreen workspace'}).tap()
  const controls=page.getByRole('navigation',{name:'Fullscreen controls'})
  await controls.getByRole('button',{name:'Chat',exact:true}).tap()
  await expect(page.locator('.chat-panel')).toHaveClass(/popped-out/)
  for(const selector of ['.focus-controls','.chat-panel']) {
    const box=(await page.locator(selector).boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(402)
    expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(874)
  }
  await controls.getByRole('button',{name:'Decisions',exact:true}).tap()
  const box=(await page.locator('.decision-workspace').boundingBox())!
  expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(402)
  expect(box.y+box.height).toBeLessThanOrEqual(874)
  await controls.getByRole('button',{name:'Exit fullscreen'}).tap()
  await expect(page.getByRole('navigation',{name:'Workspace actions'})).toBeVisible()
})

test('iPhone-sized forms use safe text sizing and scroll independently of diagram zoom', async ({ page, browserName }) => {
  await page.goto('/')
  await expect(page.locator('.preview-content svg .node').first()).toBeVisible()
  // Fix the camera before comparing scroll behavior; initial auto-fit is asynchronous.
  await page.getByTitle('Reset Zoom').tap()
  await expect(page.locator('.zoom-level')).toHaveText('100%')
  const zoom = await page.locator('.zoom-level').textContent()
  await page.getByTitle('Settings').tap()
  const input = page.locator('#ollama-model')
  await input.tap()
  await expect(input).toBeFocused()
  expect(await input.evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
  await page.getByRole('tab', { name: 'Generation', exact: true }).tap()
  const fields = page.locator('.settings-modal input:not([type=checkbox]):visible, .settings-modal textarea:visible, .settings-modal select:visible')
  for (const field of await fields.all()) {
    expect(await field.evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
  }
  await page.getByRole('tab', { name: 'Connection', exact: true }).tap()
  const content = page.locator('.settings-content')
  if (browserName === 'webkit') {
    // Playwright cannot inject native wheel or swipe gestures into mobile WebKit.
    expect(await content.evaluate(element => getComputedStyle(element).touchAction)).toContain('pan-y')
    await content.evaluate(element => { element.scrollTop = 400 })
  } else {
    await content.hover()
    await page.mouse.wheel(0, 400)
  }
  await expect.poll(() => content.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  expect(await page.locator('.zoom-level').textContent()).toBe(zoom)
  expect(await page.evaluate(() => window.visualViewport!.scale)).toBe(1)
  await page.getByRole('button', { name: 'Close settings' }).tap()
  await page.getByTitle('Decisions (Preview)').tap()
  expect(await page.locator('#flow-goal').evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
  await page.getByRole('button', { name: 'Close decision workspace' }).tap()
  await page.getByTitle('Toggle AI Chat').tap()
  const chatInput = page.locator('.chat-input-form textarea')
  expect(await chatInput.evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
})

test('keyboard viewport changes keep settings controls visible and restore the layout without resetting browser zoom', async ({ page }) => {
  await page.addInitScript(() => {
    const viewport = Object.assign(new EventTarget(), { height: 874, width: 402, offsetTop: 0, offsetLeft: 0, pageTop: 0, pageLeft: 0, scale: 1 })
    Object.defineProperty(window, 'visualViewport', { value: viewport, configurable: true })
  })
  await page.goto('/')
  await page.getByTitle('Settings').tap()
  await page.locator('#ollama-model').tap()
  await page.evaluate(() => {
    Object.assign(window.visualViewport!, { height: 390, offsetTop: 40 })
    window.visualViewport!.dispatchEvent(new Event('resize'))
  })
  await expect.poll(() => page.locator('.app').evaluate(element => element.getBoundingClientRect().height)).toBe(390)
  const bounds = (await page.getByRole('dialog', { name: 'Settings' }).boundingBox())!
  expect(bounds.y).toBeGreaterThanOrEqual(40)
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(430)
  const save = (await page.locator('#settings-save').boundingBox())!
  expect(save.y + save.height).toBeLessThanOrEqual(430)
  await page.evaluate(() => {
    Object.assign(window.visualViewport!, { height: 874, offsetTop: 0 })
    window.visualViewport!.dispatchEvent(new Event('resize'))
  })
  await expect.poll(() => page.locator('.app').evaluate(element => element.getBoundingClientRect().height)).toBe(874)
  await page.evaluate(() => {
    Object.assign(window.visualViewport!, { height: 437, scale: 2 })
    window.visualViewport!.dispatchEvent(new Event('resize'))
  })
  expect(await page.locator('.app').evaluate(element => element.getBoundingClientRect().height)).toBe(874)
  expect(await page.evaluate(() => window.visualViewport!.scale)).toBe(2)
})

test('two-finger touch pans and pinches the diagram without rerendering; tapping a node still works', async ({ page, browserName }) => {
  test.skip(browserName !== 'chromium', 'Multi-touch injection requires the Chromium protocol; WebKit runs the form and viewport cases.')
  await page.goto('/')
  await expect(page.locator('.preview-content svg .node').first()).toBeVisible()
  const id = await page.locator('.preview-content svg').getAttribute('id')
  const zoom = await page.locator('.zoom-level').textContent()
  const viewport = (await page.locator('.preview-viewport').boundingBox())!
  const x = Math.round(viewport.x + viewport.width / 2), y = Math.round(viewport.y + viewport.height / 2)
  const client = await page.context().newCDPSession(page)
  const touch = async (type: 'touchStart' | 'touchMove' | 'touchEnd', points: { x: number; y: number; id: number }[]) => {
    await client.send('Input.dispatchTouchEvent', { type, touchPoints: points })
  }
  await touch('touchStart', [{ x: x - 40, y, id: 1 }, { x: x + 40, y, id: 2 }])
  await touch('touchMove', [{ x: x - 40, y: y - 45, id: 1 }, { x: x + 40, y: y - 45, id: 2 }])
  await touch('touchEnd', [])
  expect(await page.locator('.zoom-level').textContent()).toBe(zoom)
  const shifted = await page.locator('.preview-content').evaluate(element => getComputedStyle(element).transform)
  expect(shifted).not.toBe('matrix(1, 0, 0, 1, 0, 0)')
  await touch('touchStart', [{ x: x - 40, y, id: 1 }, { x: x + 40, y, id: 2 }])
  await touch('touchMove', [{ x: x - 65, y, id: 1 }, { x: x + 65, y, id: 2 }])
  await touch('touchEnd', [])
  await expect(page.locator('.zoom-level')).not.toHaveText(zoom!)
  expect(await page.locator('.preview-content svg').getAttribute('id')).toBe(id)
  await page.getByTitle('Reset Zoom').tap()
  await page.waitForTimeout(450)
  await page.locator('.preview-content svg .node').first().tap()
  await expect.poll(() => page.evaluate(() => (window as any).monaco.editor.getEditors()[0].getSelection().startLineNumber)).toBe(2)
  await client.detach()
})

test('ordinary two-finger trackpad scrolling pans; Ctrl-wheel zooms only the diagram', async ({ page, browserName }) => {
  test.skip(browserName === 'webkit', 'Playwright does not support wheel injection in mobile WebKit; Chromium verifies trackpad gestures.')
  await page.goto('/')
  await expect(page.locator('.preview-content svg .node').first()).toBeVisible()
  const id = await page.locator('.preview-content svg').getAttribute('id')
  const zoom = await page.locator('.zoom-level').textContent()
  await page.locator('.preview-viewport').hover()
  await page.mouse.wheel(30, 80)
  await expect.poll(() => page.locator('.preview-content').evaluate(element => getComputedStyle(element).transform)).not.toBe('matrix(1, 0, 0, 1, 0, 0)')
  expect(await page.locator('.zoom-level').textContent()).toBe(zoom)
  await page.keyboard.down('Control')
  await page.mouse.wheel(0, -60)
  await page.keyboard.up('Control')
  await expect(page.locator('.zoom-level')).not.toHaveText(zoom!)
  expect(await page.evaluate(() => window.visualViewport!.scale)).toBe(1)
  expect(await page.locator('.preview-content svg').getAttribute('id')).toBe(id)
})

test('mobile decision cards support a real touch choice and focus the next question without page zoom',async({page})=>{
  const {readFile}=await import('node:fs/promises')
  const fixture=await readFile(new URL('../../docs/fixtures/decision-acceptance.de.decision.json',import.meta.url))
  await page.goto('/')
  await page.getByTitle('Decisions (Preview)').tap()
  await page.getByText('Save / load flow',{exact:true}).tap()
  await page.getByLabel('Decision JSON file').setInputFiles({name:'acceptance.json',mimeType:'application/json',buffer:fixture})
  await expect(page.getByRole('button',{name:'Decide',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Go to current question',exact:true}).tap()
  await page.getByRole('region',{name:'Question: Welcher Budgetzustand wird ausdrücklich beschrieben?'}).getByRole('button',{name:'Choose Budget ausdrücklich freigegeben',exact:true}).tap()
  await expect(page.locator('#question-card-stufe')).toBeFocused()
  const score=page.getByRole('region',{name:'Question: Welche Freigabestufe ist durch die aktuellen Fakten belegt?'})
  await score.getByRole('button',{name:'Choose Unklar / prüfen',exact:true}).tap()
  await expect(page.locator('#question-card-aussage')).toBeFocused()
  expect(await page.evaluate(()=>window.scrollY)).toBe(0)
  expect(await page.evaluate(()=>window.visualViewport!.scale)).toBe(1)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('mobile review confirmation advances in order without keyboard zoom',async({page})=>{
  const {readFile}=await import('node:fs/promises')
  const fixture=await readFile(new URL('../../docs/fixtures/decision-acceptance.de.decision.json',import.meta.url))
  await page.goto('/')
  await page.getByTitle('Decisions (Preview)').tap()
  await page.getByText('Save / load flow',{exact:true}).tap()
  await page.getByLabel('Decision JSON file').setInputFiles({name:'acceptance.json',mimeType:'application/json',buffer:fixture})
  const budget=page.getByRole('region',{name:'Question: Welcher Budgetzustand wird ausdrücklich beschrieben?'})
  const score=page.getByRole('region',{name:'Question: Welche Freigabestufe ist durch die aktuellen Fakten belegt?'})
  await budget.getByRole('button',{name:'Choose Budget ausdrücklich freigegeben',exact:true}).tap()
  await score.getByRole('button',{name:'Choose Unklar / prüfen',exact:true}).tap()
  await page.locator('#flow-context').fill('Das Budget ist inzwischen abgelehnt; die Tests sind fehlgeschlagen.')
  await expect(score.getByRole('button',{name:'Confirm previous answer',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'Go to current question',exact:true}).tap()
  await budget.getByRole('button',{name:'Choose Budget ausdrücklich abgelehnt',exact:true}).tap()
  await expect(page.locator('#question-card-stufe')).toBeFocused()
  await expect(score.getByRole('button',{name:'Confirm previous answer',exact:true})).toBeEnabled()
  await score.getByRole('button',{name:'Choose Blockiert',exact:true}).tap()
  await expect(page.getByRole('region',{name:'Answers awaiting review'})).toHaveCount(0)
  expect(await page.evaluate(()=>window.scrollY)).toBe(0)
  expect(await page.evaluate(()=>window.visualViewport!.scale)).toBe(1)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
