import {test,expect} from '@playwright/test'
test('combined template, reviewed updates, replay and reports survive a real browser workflow',async({page})=>{
 await page.goto('/');await page.getByTitle('Decisions (Preview)').click()
 await page.getByLabel('Example flow').selectOption('release')
 await page.getByRole('button',{name:'Edit flow',exact:true}).click()
 await page.getByRole('button',{name:'Choose Passed',exact:true}).click()
 await page.getByRole('button',{name:'Choose Approved',exact:true}).click()
 await page.getByRole('button',{name:'Choose Public',exact:true}).click()
 await page.getByText('Reports, replay & external updates',{exact:true}).click()
 const current=await page.evaluate(()=>JSON.parse(localStorage.getItem('mermaider-tabs')!).find((tab:any)=>tab.id===localStorage.getItem('mermaider-active-tab')).decision)
 const update={format:'mermaider-state-update',version:1,id:'review-test',sessionId:current.id,expectedRevision:current.revision,state:'Publication approval was revoked.',source:'External test'}
 const file={name:'state-update.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(update))}
 await page.getByLabel('External state update file').setInputFiles(file)
 await expect(page.getByRole('region',{name:'External update preview'})).toContainText(update.state)
 await expect(page.locator('#flow-context')).not.toHaveValue(update.state)
 await page.getByRole('button',{name:'Apply reviewed state update',exact:true}).click()
 await expect(page.locator('#flow-context')).toHaveValue(update.state)
 await expect(page.getByRole('button',{name:'Choose Public',exact:true})).toBeDisabled()
 await page.getByLabel('External state update file').setInputFiles(file)
 await expect(page.getByRole('button',{name:'Apply reviewed state update',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'Discard update',exact:true}).click()
 const options=await page.getByLabel('Replay snapshot').locator('option').allTextContents()
 expect(options.some(value=>value.includes('Selected answer'))).toBeTruthy()
 await page.getByLabel('Replay snapshot').selectOption({index:1})
 await page.getByRole('button',{name:'Restore snapshot',exact:true}).click()
 await expect(page.locator('#flow-context')).not.toHaveValue(update.state)
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export state report',exact:true}).click()
 expect((await download).suggestedFilename()).toBe('decision-report.json')
 await page.reload();await page.getByTitle('Decisions (Preview)').click()
 await expect(page.locator('.preview-container svg')).toContainText('Which release channel?')
})
test('custom shortcuts and local relay preference are accessible and persist without credentials',async({page})=>{
 await page.goto('/');await page.getByTitle('Settings').click()
 const dialog=page.getByRole('dialog',{name:'Settings'})
 await dialog.getByRole('tab',{name:'Appearance',exact:true}).click()
 await dialog.getByText('Keyboard shortcuts',{exact:true}).click()
 await dialog.getByLabel('Search diagrams shortcut').fill('Mod+Shift+k')
 await dialog.getByRole('button',{name:'Apply shortcuts',exact:true}).click()
 await expect(dialog.getByRole('status')).toContainText('Shortcuts saved.')
 await dialog.getByRole('tab',{name:'Connection',exact:true}).click()
 await dialog.getByText('Optional streaming relay',{exact:true}).click()
 await dialog.getByLabel('Use the local streaming relay').check()
 await dialog.getByRole('button',{name:'Save transport preference',exact:true}).click()
 expect(await page.evaluate(()=>localStorage.getItem('mermaider-streaming-gateway'))).toBe('http://127.0.0.1:8003')
 await page.getByRole('button',{name:'Close settings',exact:true}).click()
 await page.keyboard.press('Control+Shift+k')
 await expect(page.getByRole('dialog',{name:'Your diagrams'})).toBeVisible()
 await page.keyboard.press('Escape');await page.reload()
 await page.keyboard.press('Control+Shift+k')
 await expect(page.getByRole('dialog',{name:'Your diagrams'})).toBeVisible()
})
