import { test, expect } from '@playwright/test'

test('submenu actions survive transient blur and work with pointer and keyboard', async ({ page }) => {
  await page.goto('/')
  await page.getByTitle('Pop out',{exact:true}).click()
  await page.getByRole('button', { name:'View', exact:true }).click()
  // Webviews can report no relatedTarget during pointer focus changes.
  await page.getByRole('menuitem', { name:'Switch to light theme' }).evaluate(element => element.dispatchEvent(new FocusEvent('focusout', { bubbles:true, relatedTarget:null })))
  await page.getByRole('menuitem', { name:'Switch to light theme' }).click()
  await expect(page.locator('.app')).toHaveClass(/light/)
  await page.getByRole('button', { name:'File', exact:true }).click()
  await page.getByRole('menuitem', { name:'Knowledge base / RAG…' }).click()
  await expect(page.getByRole('heading', { name:'Knowledge Base & Quick Import' })).toBeVisible()
  await page.locator('.kb-header .close-button').click()
  await page.getByRole('button', { name:'View', exact:true }).focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await expect(page.locator('.help-modal')).toBeVisible()
})

test('many diagrams use one compact switcher and search names and live Mermaid content', async ({ page }) => {
  await page.addInitScript(() => {
    const tabs = Array.from({length:30}, (_,i) => ({id:`diagram-${i}`,name:`Project ${i}`,code:`graph TD\n A[${i===17?'Authorization token renewed':'Start '+i}] --> B[End]`,chatSessions:[{id:`chat-${i}`,messages:[],timestamp:1}],activeChatSessionId:`chat-${i}`}))
    if (!localStorage.getItem('mermaider-tabs')) {
      localStorage.setItem('mermaider-tabs', JSON.stringify(tabs))
      localStorage.setItem('mermaider-active-tab','diagram-0')
    }
  })
  await page.goto('/')
  await expect(page.locator('.diagram-switcher')).toHaveAttribute('data-diagram-count','30')
  await expect(page.locator('.tab-bar')).toHaveCount(0)
  await expect(page.getByRole('navigation',{name:'Workspace actions'}).locator('.diagram-library-trigger')).toBeVisible()
  const before = await page.locator('.diagram-library-trigger').boundingBox()
  expect(before!.height).toBeLessThanOrEqual(48)
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog',{name:'Your diagrams'})
  const search = dialog.getByRole('searchbox',{name:'Search diagrams'})
  await expect(search).toBeFocused()
  await search.fill('AUTHORIZATION renewed')
  await expect(dialog.locator('.diagram-result-select')).toHaveCount(1)
  await expect(dialog.locator('.diagram-result-select')).toContainText('L2 · A[Authorization token renewed]')
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.current-diagram')).toHaveText('Project 17')
  await expect(page.locator('.preview-content svg')).toContainText('Authorization token renewed')
  await page.getByRole('button',{name:/^Diagrams/}).click()
  await search.fill('Project 29')
  await page.keyboard.press('ArrowDown')
  await expect(dialog.getByRole('button',{name:'Open diagram: Project 29'})).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('.current-diagram')).toHaveText('Project 29')
  await page.getByRole('button',{name:/^Diagrams/}).click()
  await search.fill('nothing-matches-this')
  await expect(dialog.getByText('No matching diagrams. Try another name or phrase.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:/^Diagrams/})).toBeFocused()
  await page.getByRole('button',{name:/^Diagrams/}).click()
  await dialog.getByRole('button',{name:'Close diagram: Project 29',exact:true}).click()
  await expect(page.locator('.diagram-switcher')).toHaveAttribute('data-diagram-count','29')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.current-diagram')).toHaveText('Project 28')
})

test('fullscreen keeps drafts and decisions, floating panels move and exiting restores the workspace', async ({ page }) => {
  await page.goto('/')
  const chatInput=page.locator('.chat-input-form textarea')
  await chatInput.fill('Keep this unsent draft')
  await page.getByRole('button',{name:'View',exact:true}).click()
  await page.getByRole('menuitem',{name:'Fullscreen workspace'}).click()
  const controls=page.getByRole('navigation',{name:'Fullscreen controls'})
  await expect(controls).toBeVisible()
  await expect(page.getByRole('navigation',{name:'Workspace actions'})).toBeHidden()
  await expect(page.locator('.diagram-switcher')).toBeHidden()
  await expect(page.locator('.editor-container')).toHaveCount(0)
  await expect(page.locator('.preview-header')).toBeHidden()
  await expect(chatInput).toHaveValue('Keep this unsent draft')
  await expect(page.locator('.chat-panel')).toHaveClass(/popped-out/)
  const viewport=(await page.locator('.preview-viewport').boundingBox())!
  expect(viewport.width).toBe(1440)
  const header=page.getByLabel('Move chat window (arrow keys or drag)')
  const before=(await page.locator('.chat-panel').boundingBox())!
  await header.focus(); await page.keyboard.press('ArrowRight')
  expect((await page.locator('.chat-panel').boundingBox())!.x).toBe(before.x+20)
  await controls.getByRole('button',{name:'Exit fullscreen'}).click()
  await expect(page.getByRole('navigation',{name:'Workspace actions'})).toBeVisible()
  await expect(page.locator('.editor-container')).toBeVisible()
  await expect(chatInput).toHaveValue('Keep this unsent draft')
  await page.getByTitle('Pop out', {exact:true}).click()
  await page.getByTitle('Settings').click()
  const settings=page.getByRole('dialog',{name:'Settings'})
  await expect(settings).toBeVisible()
  const floating=(await page.locator('.chat-panel').boundingBox())!
  expect(await page.evaluate(({x,y}) => !!document.elementFromPoint(x,y)?.closest('.modal-overlay'), {x:floating.x+30,y:floating.y+30})).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByTitle('Dock', {exact:true}).click()
  await page.getByTitle('Decisions (Preview)').click()
  await page.locator('#flow-goal').fill('Keep decision context')
  await page.getByRole('button',{name:'Pop out decisions'}).click()
  await expect(page.locator('.decision-workspace')).toHaveClass(/floating/)
  await page.getByRole('button',{name:'Dock decisions'}).click()
  await expect(page.locator('.decision-workspace')).not.toHaveClass(/floating/)
  await page.getByRole('button',{name:'View',exact:true}).click()
  await page.getByRole('menuitem',{name:'Fullscreen workspace'}).click()
  await expect(page.locator('.decision-workspace')).toHaveClass(/floating/)
  await expect(page.locator('#flow-goal')).toHaveValue('Keep decision context')
  await controls.getByRole('button',{name:'Decisions',exact:true}).click()
  await expect(page.locator('.decision-workspace')).toHaveCount(0)
  await expect(chatInput).toHaveValue('Keep this unsent draft')
  await controls.getByRole('button',{name:'Decisions',exact:true}).click()
  await expect(page.locator('#flow-goal')).toHaveValue('Keep decision context')
  if(await page.evaluate(()=>!!document.fullscreenElement)) await page.evaluate(()=>document.exitFullscreen())
  else await page.keyboard.press('Escape')
  await expect(controls).toHaveCount(0)
  await expect(page.locator('.decision-workspace')).not.toHaveClass(/floating/)
})

test('fullscreen gracefully falls back and cannot exit through a search dialog Escape', async ({ page }) => {
  await page.addInitScript(()=>{Object.defineProperty(document,'fullscreenEnabled',{value:false})})
  await page.goto('/')
  await page.getByRole('button',{name:'View',exact:true}).click()
  await page.getByRole('menuitem',{name:'Fullscreen workspace'}).click()
  const controls=page.getByRole('navigation',{name:'Fullscreen controls'})
  await controls.getByRole('button',{name:'Diagrams',exact:true}).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog',{name:'Your diagrams'})).toHaveCount(0)
  await expect(controls).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(controls).toHaveCount(0)
})

test('desktop fullscreen calls the native window API and returns to windowed mode', async ({ page }) => {
  await page.addInitScript(() => {
    const native = window as unknown as { __TAURI_INTERNALS__: unknown; fullscreenCalls: boolean[] }
    native.fullscreenCalls = []
    native.__TAURI_INTERNALS__ = {
      metadata: {currentWindow:{label:'main'}},
      invoke: async (command: string, args: {value?:boolean}) => {
        if(command === 'plugin:window|set_fullscreen') native.fullscreenCalls.push(args.value!)
        return null
      }
    }
  })
  await page.goto('/')
  await page.getByRole('button',{name:'View',exact:true}).click()
  await page.getByRole('menuitem',{name:'Fullscreen workspace'}).click()
  await expect.poll(()=>page.evaluate(()=>(window as unknown as {fullscreenCalls:boolean[]}).fullscreenCalls)).toEqual([true])
  await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>(window as unknown as {fullscreenCalls:boolean[]}).fullscreenCalls)).toEqual([true,false])
  await expect(page.locator('.editor-container')).toBeVisible()
})
