import type {FlowPlan,FlowQuestion} from '../decision/flow'
interface Props {plan:FlowPlan;question:FlowQuestion;onChange:(question:FlowQuestion)=>void}
export default function DecisionRequirements({plan,question,onChange}:Props){
  const reaches=(start:string|undefined,seen=new Set<string>()):boolean=>{if(!start||seen.has(start))return false;if(start===question.id)return true;seen.add(start);return plan.questions.find(item=>item.id===start)!.options.some(option=>reaches(option.nextId,seen))}
  const candidates=plan.questions.filter(item=>item.id!==question.id).flatMap(item=>item.options.filter(option=>reaches(option.nextId)).map(option=>({questionId:item.id,optionId:option.id,label:`${item.text}: ${option.label}`})))
  const requirements=question.requirements
  if(!candidates.length&&!requirements)return null
  return <details><summary>Combined requirements</summary><p>Only confirmed preceding answers count. Requirements pause this question until they are met.</p>
    {requirements&&<><label>Combine requirements<select aria-label={`Requirement mode for ${question.text}`} value={requirements.mode} onChange={event=>onChange({...question,requirements:{...requirements,mode:event.target.value as 'all'|'any'}})}><option value="all">All (AND)</option><option value="any">Any (OR)</option></select></label>
    {requirements.answers.map((answer,index)=><div className="flow-option" key={index}><select aria-label={`Requirement ${index+1} for ${question.text}`} value={JSON.stringify([answer.questionId,answer.optionId])} onChange={event=>{const [questionId,optionId]=JSON.parse(event.target.value);onChange({...question,requirements:{...requirements,answers:requirements.answers.map((item,i)=>i===index?{questionId,optionId}:item)}})}}>{candidates.map(item=><option key={JSON.stringify([item.questionId,item.optionId])} value={JSON.stringify([item.questionId,item.optionId])}>{item.label}</option>)}</select><button aria-label={`Remove requirement ${index+1}`} onClick={()=>{const answers=requirements.answers.filter((_,i)=>i!==index);onChange({...question,requirements:answers.length?{...requirements,answers}:undefined})}}>×</button></div>)}</>}
    <button disabled={(requirements?.answers.length||0)>=12||!candidates.some(candidate=>!requirements?.answers.some(item=>item.questionId===candidate.questionId&&(requirements.mode==='all'||item.optionId===candidate.optionId)))} onClick={()=>{const candidate=candidates.find(candidate=>!requirements?.answers.some(item=>item.questionId===candidate.questionId&&(requirements.mode==='all'||item.optionId===candidate.optionId)))!;onChange({...question,requirements:{mode:requirements?.mode||'all',answers:[...(requirements?.answers||[]),{questionId:candidate.questionId,optionId:candidate.optionId}]}})}}>+ Requirement</button>
  </details>
}
